/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.Employee_BUS;
import DTO.Employee_DTO;
import DAO.Employee_DAO;
import DAO.JDBC;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mai
 */
public class Employee extends javax.swing.JFrame {
    Employee_BUS nvBUS = new Employee_BUS();
    Connection con;
    public Employee() {
        initComponents();
        this.con = JDBC.getConnection();
        addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowOpened(java.awt.event.WindowEvent evt) {
            formWindowOpened();
        }
    });
        loadList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNhanVien = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnADD = new javax.swing.JButton();
        btnEDIT = new javax.swing.JButton();
        btnDEL = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        txtFind = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDate = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jButtonload = new javax.swing.JButton();
        jButtonupdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(213, 192, 165));
        jPanel1.setPreferredSize(new java.awt.Dimension(720, 516));

        jTableNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MaNV", "MaCapBac", "HoTen", "NgaySinh", "GioiTinh", "SDT"
            }
        ));
        jTableNhanVien.setShowGrid(true);
        jScrollPane1.setViewportView(jTableNhanVien);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText(" Nhân viên");

        btnADD.setText("Thêm");
        btnADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDActionPerformed(evt);
            }
        });

        btnEDIT.setText("Sửa");
        btnEDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEDITActionPerformed(evt);
            }
        });

        btnDEL.setText("Xóa");
        btnDEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDELActionPerformed(evt);
            }
        });

        btnFind.setText("Tìm");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Họ Tên");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Ngày Sinh");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Điện Thoại");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Cấp Bậc");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton5.setText("Thoát");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Giới Tính");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "Khác" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Mã NV");

        jButtonload.setText("Loading");
        jButtonload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonloadActionPerformed(evt);
            }
        });

        jButtonupdate.setText("Cập nhật");
        jButtonupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonupdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtID)
                                    .addComponent(txtDate, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(63, 63, 63)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnADD)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnDEL, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnEDIT)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonupdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtName))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(45, 45, 45)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFind))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonload)
                            .addComponent(btnADD))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEDIT)
                            .addComponent(jButtonupdate))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDEL)
                            .addComponent(jButton5)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Staff st = new Staff();
        st.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDActionPerformed
       try {
        if (txtName.getText().isEmpty() || txtDate.getDate() == null || txtSDT.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin");
            return;
        }

        String sdtStr = txtSDT.getText().trim();

        // Kiểm tra SDT chỉ chứa số và có đúng 10 chữ số
        if (!sdtStr.matches("\\d{9,10}")) { 
            JOptionPane.showMessageDialog(this, "Số điện thoại phải là số và có 9 hoặc 10 chữ số!");
            return;
        }
        
        java.sql.Date ngaySinh = new java.sql.Date(txtDate.getDate().getTime());
        // Kiểm tra nhân viên đủ 18 tuổi chưa
        LocalDate birthDate = ngaySinh.toLocalDate();
        LocalDate today = LocalDate.now();
        Period age = Period.between(birthDate, today);

        if (age.getYears() < 18) {
            JOptionPane.showMessageDialog(this, "Nhân viên phải đủ 18 tuổi trở lên!");
            return;
        }

        Employee_DTO nv = new Employee_DTO();

        // **Chuyển đổi MaNV từ int sang String**
        int newMaNV = generateMaNV(); // Hàm tạo mã số mới
        nv.setMaNV(newMaNV); // Chuyển thành String để truyền vào DTO

        // **Chuyển đổi MaCapBac từ String sang int**
        int newMaCapBac = Integer.parseInt(jComboBox1.getSelectedItem().toString());
        nv.setMaCapBac(newMaCapBac); // Lưu lại dưới dạng String để tránh lỗi

        nv.setHoTen(txtName.getText());
        nv.setNgaySinh(ngaySinh);
        nv.setGioiTinh((String) jComboBox2.getSelectedItem());
        nv.setSDT(sdtStr);  // Sử dụng String thay vì int

        // **Gửi xuống BUS để thêm vào DB**
        String result = nvBUS.addNV(nv);
        JOptionPane.showMessageDialog(this, result);
        if (result.equals("Thêm thành công!")) {
            txtID.setText(String.valueOf(generateMaNV()));  // Cập nhật ID mới sau khi thêm
        }
        loadList();      

        // **Reset form**
   
        txtName.setText("");
        txtDate.setDate(null);
        txtSDT.setText("");
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Mã cấp bậc phải là số!");
    } catch (Exception e) {
        e.printStackTrace();
    }
    }                                      

    private int generateMaNV() {
    return nvBUS.generateMaNV();
    }//GEN-LAST:event_btnADDActionPerformed

                                      
//---------------------------tim kiem ne --------------
                                       
    
        
    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnEDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEDITActionPerformed
        int selected = jTableNhanVien.getSelectedRow();
if (selected != -1) {
    try {
        // Lấy ID từ bảng
        String id = jTableNhanVien.getValueAt(selected, 0).toString();
        String query = "SELECT * FROM NhanVien WHERE MaNV = ?";
        
        PreparedStatement ps = con.prepareStatement(query);
        ps.setInt(1, Integer.parseInt(id)); // Chuyển ID thành int nếu cần
        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            txtID.setText(rs.getString("MaNV")); 
            jComboBox1.setSelectedItem(rs.getString("MaCapBac"));
            txtName.setText(rs.getString("HoTen"));
            
            // Chuyển đổi ngày sinh
            java.sql.Date sqlDate = rs.getDate("NgaySinh");
            if (sqlDate != null) {
                java.util.Date utilDate = new java.util.Date(sqlDate.getTime());
                txtDate.setDate(utilDate);  // Đưa vào JDateChooser
            } else {
                txtDate.setDate(null);
            }

            jComboBox2.setSelectedItem(rs.getString("GioiTinh"));
            txtSDT.setText(rs.getString("SDT"));
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi khi lấy dữ liệu nhân viên!");
    }

} else {
    JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên để chỉnh sửa!");
}
    }//GEN-LAST:event_btnEDITActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
        String selectedMaNV = (String) txtFind.getText();
        if(selectedMaNV != null){
            searchNV(selectedMaNV);
        }
    }//GEN-LAST:event_btnFindActionPerformed

    private void jButtonloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonloadActionPerformed
        // TODO add your handling code here:
        loadList();
        txtDate.setDate(null);
        txtFind.setText("");
        txtID.setText(String.valueOf(generateMaNV()));
        txtName.setText("");
        txtSDT.setText("");
    }//GEN-LAST:event_jButtonloadActionPerformed

    private void jButtonupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonupdateActionPerformed
        int selected = jTableNhanVien.getSelectedRow();
    if (selected != -1) {
        try {
            int id = Integer.parseInt(txtID.getText());
            int newCapBac = Integer.parseInt(jComboBox1.getSelectedItem().toString());            
            String newName = txtName.getText();

            if (txtDate.getDate() == null) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày sinh!");
                return;
            }
            java.sql.Date newBirthday = new java.sql.Date(txtDate.getDate().getTime());

            String newGioiTinh = (String) jComboBox2.getSelectedItem();

            // Kiểm tra số điện thoại hợp lệ (9 hoặc 10 chữ số)
            String newSDT = txtSDT.getText().trim();
            if (!newSDT.matches("\\d{9,10}")) {
                JOptionPane.showMessageDialog(this, "Số điện thoại phải có 9 hoặc 10 chữ số!");
                return;
            }

            // Tạo đối tượng Employee_DTO
            Employee_DTO nv = new Employee_DTO(id, newCapBac, newName, newBirthday, newGioiTinh, newSDT);

            // Gọi phương thức cập nhật từ BUS
            String result = nvBUS.updateNV(nv);
            JOptionPane.showMessageDialog(this, result);

            // Cập nhật lại danh sách nhân viên trên bảng
            loadList();
            txtID.setText(String.valueOf(generateMaNV()));
            txtName.setText("");
            txtDate.setDate(null);
            txtSDT.setText("");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Có lỗi xảy ra! Vui lòng kiểm tra lại.");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên cần cập nhật!");
    }
    }//GEN-LAST:event_jButtonupdateActionPerformed

    private void btnDELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDELActionPerformed
        int select = jTableNhanVien.getSelectedRow();
        if (select != -1)
        {
            int id = Integer.parseInt(jTableNhanVien.getValueAt(select , 0).toString());
            int kq = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa ?");
            if (kq == JOptionPane.YES_OPTION)
            {
                nvBUS.deleteNV(id);
                ((DefaultTableModel) jTableNhanVien.getModel()).removeRow(select);
                formWindowOpened();
                loadList();
                
            }
        }
    }//GEN-LAST:event_btnDELActionPerformed
    private void searchNV(String manv){
         Employee_DTO sp = nvBUS.findbyID(Integer.parseInt(manv));
    if (sp != null) {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("MaNV");
        model.addColumn("MaCapBac");
        model.addColumn("HoTen");
        model.addColumn("NgaySinh");
        model.addColumn("GioiTinh");
        model.addColumn("SDT");

        // Chuyển đổi ngày sinh về dạng java.util.Date nếu cần
        java.util.Date ngaySinh = (sp.getNgaySinh() != null) ? new java.util.Date(sp.getNgaySinh().getTime()) : null;

        model.addRow(new Object[]{
            sp.getMaNV(),
            sp.getMaCapBac(),
            sp.getHoTen(),
            ngaySinh, // Đã chuyển đổi về java.util.Date
            sp.getGioiTinh(),
            String.valueOf(sp.getSDT()) // Chuyển int thành String
        });

        jTableNhanVien.setModel(model);

        // Đổ dữ liệu vào các ô nhập
        txtID.setText(String.valueOf(sp.getMaNV()));
        jComboBox1.setSelectedItem(sp.getMaCapBac());
        txtName.setText(sp.getHoTen());
        txtDate.setDate(ngaySinh); // Đã kiểm tra null
        jComboBox2.setSelectedItem(sp.getGioiTinh()); 
        txtSDT.setText(String.valueOf(sp.getSDT())); // Chuyển int thành String
    } else {
        JOptionPane.showMessageDialog(this, "Không tìm thấy nhân viên!");
    }

    }

    private void formWindowOpened() {                                     
    txtID.setText(String.valueOf(generateMaNV()));
     txtID.setEditable(false);// Cập nhật ID mới khi mở form
    }
    
    private void loadList() {
        Vector<Employee_DTO> nccList = new Vector<Employee_DTO>();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("MaNV");
        model.addColumn("MaCapBac");
        model.addColumn("HoTen");        
        model.addColumn("NgaySinh");
        model.addColumn("GioiTinh");
        model.addColumn("SDT");
        
        nccList = nvBUS.getALLnv();
        for (int i = 0; i < nccList.size(); i++)
        {
            Employee_DTO ncc = new Employee_DTO();
            ncc = nccList.get(i);
            int idNV = ncc.getMaNV();
            int MaCapBac = ncc.getMaCapBac();
            String HoTen = ncc.getHoTen();
            Date NgaySinh = ncc.getNgaySinh();
            String GioiTinh = ncc.getGioiTinh();
            String SDT = ncc.getSDT();

            Object[] row = {idNV, MaCapBac, HoTen, NgaySinh, GioiTinh,SDT};
            model.addRow(row);
        }
        jTableNhanVien.setModel(model);
                
    }
   


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnADD;
    private javax.swing.JButton btnDEL;
    private javax.swing.JButton btnEDIT;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonload;
    private javax.swing.JButton jButtonupdate;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableNhanVien;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JTextField txtFind;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSDT;
    // End of variables declaration//GEN-END:variables
}
