/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.Employee_BUS;
import BUS.Hierarchy_BUS;
import BUS.Payroll_BUS;
import BUS.Schedule_BUS;
import DTO.Payroll_DTO;
import DTO.Schedule_DTO;
import java.awt.event.ActionListener;
import java.io.FileOutputStream;
import java.io.IOException;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Mai
 */
public class Payroll_NV extends javax.swing.JFrame {
    Payroll_BUS pay = new Payroll_BUS();
    Schedule_BUS sch = new Schedule_BUS();
    Employee_BUS emp = new Employee_BUS();
    Hierarchy_BUS hie = new Hierarchy_BUS();

    /**
     * Creates new form Payroll_NV
     */
    public Payroll_NV() {
        initComponents();
        try {
            populateCBNam();
        } catch (SQLException ex) {
            Logger.getLogger(Payroll_NV.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tonggio = new javax.swing.JTextField();
        songay = new javax.swing.JTextField();
        songaynghi = new javax.swing.JTextField();
        mucluong = new javax.swing.JTextField();
        tong = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Thang = new javax.swing.JComboBox<>();
        Nam = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(243, 222, 196));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Bảng lương");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Tháng");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Năm");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Tổng giờ làm");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Số ngày làm");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Số ngày nghỉ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Mức lương");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Tổng lương");

        jButton2.setText("In  theo tháng");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("In  theo năm");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Thoát");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        Thang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thang" }));
        Thang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThangActionPerformed(evt);
            }
        });

        Nam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam" }));
        Nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tonggio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(songaynghi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(songay, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(97, 97, 97)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton4)
                                .addComponent(jButton2)
                                .addComponent(jButton3)))
                        .addComponent(Nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(mucluong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(tong, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Thang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(201, 201, 201)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Thang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tonggio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton2)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(songay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(songaynghi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(mucluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            int idNV = UserSession.getInstance().getLoggedInAccount().getIDNV();
            int nam = Integer.parseInt(Nam.getSelectedItem().toString());
            
            List<Payroll_DTO> payrollList = pay.getPayrollsNVbyYear(idNV, nam);
            
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Chọn nơi lưu file Excel");
            int userSelection = fileChooser.showSaveDialog(null);
            
            if (userSelection == JFileChooser.APPROVE_OPTION) {
                String filePath = fileChooser.getSelectedFile().getAbsolutePath();
                if (!filePath.endsWith(".xlsx")) {
                    filePath += ".xlsx";
                }
                
                exportPayrollListToExcel(payrollList, filePath);
                JOptionPane.showMessageDialog(null, "Đã xuất file bảng lương!");
            }   } catch (SQLException ex) {
            Logger.getLogger(Payroll_NV.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        NVform nv = new NVform();
        nv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void NamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamActionPerformed
        // TODO add your handling code here:
        int nam=Integer.parseInt(Nam.getSelectedItem().toString());
        try {
            populateCBThang(nam);
        } catch (SQLException ex) {
            Logger.getLogger(Payroll_NV.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_NamActionPerformed

    private void ThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThangActionPerformed
        // TODO add your handling code here:
        int id = UserSession.getInstance().getLoggedInAccount().getIDNV();
        int nam=Integer.parseInt(Nam.getSelectedItem().toString());
        int thang=Integer.parseInt(Thang.getSelectedItem().toString());
        loadData(nam,thang,id);
    }//GEN-LAST:event_ThangActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            int idNV = UserSession.getInstance().getLoggedInAccount().getIDNV();
            int thang = Integer.parseInt(Thang.getSelectedItem().toString());
            int nam = Integer.parseInt(Nam.getSelectedItem().toString());
            
            Payroll_DTO payroll = pay.getPayrollsNV(idNV, thang, nam);
            
            
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Chọn nơi lưu bảng lương");
            int result = fileChooser.showSaveDialog(null);
            if (result == JFileChooser.APPROVE_OPTION) {
                String filePath = fileChooser.getSelectedFile().getAbsolutePath();
                if (!filePath.endsWith(".xlsx")) {
                    filePath += ".xlsx";
                }
                exportPayroll(payroll, filePath);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Payroll_NV.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payroll_NV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payroll_NV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payroll_NV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payroll_NV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Payroll_NV form = new Payroll_NV();
                form.setVisible(true);
                if (UserSession.getInstance().isLoggedIn()){                   
                } else {
                    new MyDialog("Bạn chưa đăng nhập!", MyDialog.ERROR_DIALOG);
                    new Login().setVisible(true);
                    form.dispose();
                }   
            }
        });
    }
    
    private void populateCBNam() throws SQLException{
        int id = UserSession.getInstance().getLoggedInAccount().getIDNV();
        ActionListener[] listeners = Nam.getActionListeners();
        for (ActionListener listener : listeners) {
            Nam.removeActionListener(listener);
        }
        Nam.removeAllItems();
        List<Integer> payrollList = pay.getAllYearsWithPayroll(id);
        for (Integer payNV : payrollList) {
            Nam.addItem(String.valueOf(payNV));
        }
        for (ActionListener listener : listeners) {
            Nam.addActionListener(listener);
        }
    }
    private void populateCBThang(int nam) throws SQLException{
        int id = UserSession.getInstance().getLoggedInAccount().getIDNV();
        ActionListener[] listeners = Thang.getActionListeners();
        for (ActionListener listener : listeners) {
            Thang.removeActionListener(listener);
        }
        Thang.removeAllItems();
        List<Payroll_DTO> payrollList = pay.getPayrollsNVbyYear(id, nam);
        for (Payroll_DTO payNV : payrollList) {
            Thang.addItem(String.valueOf(payNV.getThang()));
        }
        for (ActionListener listener : listeners) {
            Thang.addActionListener(listener);
        }
    }
    
    private void loadData(int nam, int thang, int id){
        try {
            double totalHours = 0.0; 
            Payroll_DTO payNV = pay.getPayrollsNV(id, thang, nam);
            List<Schedule_DTO> approvedSchedules = sch.fetchScheduleForEmployee(id, thang, nam);
            for (Schedule_DTO schedule : approvedSchedules) {
                long durationInMillis = schedule.getGioKetThuc().getTime() - schedule.getGioBatDau().getTime();
                double durationInHours = (double) durationInMillis / (1000 * 60 * 60);
                totalHours=totalHours+durationInHours;
            }
            tonggio.setText(String.valueOf(totalHours));
            songay.setText(String.valueOf(approvedSchedules.size()));
            songaynghi.setText(String.valueOf(payNV.getSoNgayNghi()));
            tong.setText(String.valueOf(payNV.getLuong()));            
            int macapbac = emp.getMaCapBacbyID(id);
            if (macapbac<=4) {
                mucluong.setText(String.valueOf(hie.fetchHierarchyDatabyID(macapbac).getBaseSalary()+"/tháng"));
            } else {
                mucluong.setText(String.valueOf(hie.fetchHierarchyDatabyID(macapbac).getHourlySalary()+"/h"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Payroll_NV.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void exportPayroll(Payroll_DTO payroll, String filePath) {
        Workbook workbook = new XSSFWorkbook();
        Sheet sheet = workbook.createSheet("BangLuongNV");

        // Header
        Row header = sheet.createRow(0);
        header.createCell(0).setCellValue("Mã NV");
        header.createCell(1).setCellValue("Tháng");
        header.createCell(2).setCellValue("Năm");
        header.createCell(4).setCellValue("Số ngày nghỉ");
        header.createCell(5).setCellValue("Lương");

        // Dữ liệu
        Row data = sheet.createRow(1);
        data.createCell(0).setCellValue(payroll.getMaNV());
        data.createCell(1).setCellValue(payroll.getThang());
        data.createCell(2).setCellValue(payroll.getNam());
        data.createCell(3).setCellValue(payroll.getSoNgayNghi());
        data.createCell(4).setCellValue(formatCurrency(payroll.getLuong()));

        // Ghi ra file
        try (FileOutputStream fileOut = new FileOutputStream(filePath)) {
            workbook.write(fileOut);
            JOptionPane.showMessageDialog(null, "Xuất bảng lương thành công!");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Lỗi khi xuất file: " + e.getMessage());
        }
    }
    
     public void exportPayrollListToExcel(List<Payroll_DTO> payrollList, String filePath) throws SQLException {
        Workbook workbook = new XSSFWorkbook();
        Sheet sheet = workbook.createSheet("BangLuong");
        // Ghi thông tin nhân viên
        int rowNum = 0;
        Row infoRow1 = sheet.createRow(rowNum++);
        infoRow1.createCell(0).setCellValue("Mã nhân viên:");
        infoRow1.createCell(1).setCellValue(UserSession.getInstance().getLoggedInAccount().getIDNV());

        Row infoRow2 = sheet.createRow(rowNum++);
        infoRow2.createCell(0).setCellValue("Họ tên:");
        infoRow2.createCell(1).setCellValue(emp.getTenNVByMaNV(UserSession.getInstance().getLoggedInAccount().getIDNV()));
        rowNum++;
        // Header
        String[] headers = {"Tháng", "Năm", "Số ngày nghỉ", "Tổng lương"};
        Row headerRow = sheet.createRow(rowNum++);
        for (int i = 0; i < headers.length; i++) {
            Cell cell = headerRow.createCell(i);
            cell.setCellValue(headers[i]);
        }

        // Ghi dữ liệu
        for (Payroll_DTO payroll : payrollList) {
            Row row = sheet.createRow(rowNum++);
            row.createCell(0).setCellValue(payroll.getThang());
            row.createCell(1).setCellValue(payroll.getNam());
            row.createCell(2).setCellValue(payroll.getSoNgayNghi());
            row.createCell(3).setCellValue(formatCurrency(payroll.getLuong()));
        }

        // Ghi ra file
        try (FileOutputStream fos = new FileOutputStream(filePath)) {
            workbook.write(fos);
            workbook.close();
            System.out.println("✅ Xuất file Excel thành công: " + filePath);
        } catch (IOException e) {
        }
    }
     
     private static String formatCurrency(BigDecimal amount) {
        DecimalFormatSymbols symbols = new DecimalFormatSymbols();
        symbols.setGroupingSeparator(',');
        symbols.setDecimalSeparator('.');

        DecimalFormat formatter = new DecimalFormat("#,##0.00", symbols);
        return formatter.format(amount);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Nam;
    private javax.swing.JComboBox<String> Thang;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mucluong;
    private javax.swing.JTextField songay;
    private javax.swing.JTextField songaynghi;
    private javax.swing.JTextField tong;
    private javax.swing.JTextField tonggio;
    // End of variables declaration//GEN-END:variables
}
